### ISSUE TITLE
Possibility to customize shellcheck command

### ISSUE THREAD

**Issue by cnd4** [whereswaldon/shellcheck.kak#4]
I'm using Fedora Silverblue and I run `shellcheck` through a Docker image (koalaman/shellcheck). 
I have an alias on my use shell (ZSH) for `shellcheck` but of course it doesn't work in Kakoune.

Is it possible to create an option to customize the shellcheck command so we can use an alternative way to run it?

**Comment by whereswaldon** [comment]
Hmm. This is definitely something that I'd like to support somehow. I've been meaning to try Silverblue, but I haven't gotten around to it. Could you not define a shell script available in `$PATH` to invoke the docker image, rather than using a shell alias? Something like:

```
#!/bin/sh

podman run -v <whatever> koalaman/shellcheck $@
```

If you call the above script `shellcheck` and fix the usage to actually match what you're doing with your shell alias, would it not just work?

To fix this within the plugin, I think I'd need to expose a Kakoune option for the shellcheck command. My concern there is mostly around getting the word splitting right when I go to actually execute the command, but it's not insanely complicated.

**Comment by cnd4** [comment]
I recommend you to give it a try, it's my daily desktop now and I'm very happy with it (despite the fact that we need some minor adjustments, like this one because I don't want to layer much packages).

Yeah I thought about it but I did not try right now, I'll do this today.

I'm new to Kakoune so unfortunately I can't work directly on this but if I can do anything to help, feel free to ask.

**Comment by whereswaldon** [comment]
@smumu Were you able to make the scripting approach work?

**Comment by cnd4** [comment]
Sorry, I had no internet access when I tried and I forgot to post here after.

So, I made this script:

```sh
#!/usr/bin/env sh
podman run --rm -it -v "$(pwd):/mnt:z" -w "/mnt" koalaman/shellcheck:stable $@
```

When I run it manually, on itself, I get:
```sh
❯ shellcheck shellcheck

In shellcheck line 3:
podman run --rm -it -v "$(pwd):/mnt:z" -w "/mnt" koalaman/shellcheck:stable $@
                                                                            ^-- SC2068: Double quote array expansions to avoid re-splitting elements.

For more information:
  https://www.shellcheck.net/wiki/SC2068 -- Double quote array expansions to ...
```

But when editing this file in Kakoune, I get nothing (the *SC2068* error is not visible). The `*debug*` buffer doesn't contain anything related to this plugin. 

Any idea?

**Comment by whereswaldon** [comment]
@smumu Okay, I think I've figured it out.

Firstly, the container that you're using is emitting CLRF line endings. This is super weird, as the standard shellcheck doesn't seem to do that. Perhaps it was built with windows support in mind? Regardless, I had to strip those out. This only concealed the deeper issue though:

`kak` performs linting by copying the target file into a temporary directory (in memory). This allows us to keep modifying the file during long-running lints (among other things).

The problem was that the script was mounting the current working directory into the container, but was still passing through the argument name that kakoune provided to it.

For example:

- kak creates `/tmp/xyz/text` as a temporary directory for linting
- kak copies `shellcheck` (our script) to `/tmp/xyz/text/shellcheck`
- kak issues the `lintcmd` that `shellcheck.kak` configures, which looks like `shellcheck -f gcc -x -a /tmp/xyz/text/shellcheck`
- our script translates that command into `podman run --rm -it -v "$(pwd):/mnt:z" -w /mnt koalaman/shellcheck:stable -f gcc -x -a /tmp/xyz/text/shellcheck`
- within the container, shellcheck tries to access a nonexistent file at the path `/tmp/xyz/text/shellcheck`, and it fails because that file is actually available at `/mnt/shellcheck`.

There are several possible fixes:

1. Rewrite the path of the file that kakoune passes to shellcheck so that it looks in `/mnt`. This would mean running shellcheck on the live file you're editing rather than a copy, which defeats much of the optimization that went into the linting system in the first place
2. Mount the temporary directory that kakoune created on the host system into the container at `/mnt`. This still requires us to sanitize all of the paths that kakoune provides in our arguments by rewriting `/tmp/xyz/text` to be `/mnt`. Path rewriting makes me nervous, as there are too many ways to do it wrong. Best to avoid it if there are options.
3. Mount the temporary directory that kakoune created on the host at the exact same path within the container. This allows us to avoid path rewriting and to use the temporary file that kakoune expects.

Here's a version of the script that takes the last approach:

```sh
#!/bin/sh
for lastarg in "$@"; do :; done;
dir=$(dirname "$lastarg")
podman run --rm -it -v "$dir:$dir:z" koalaman/shellcheck:stable $@ | tr -d '\r'
```

Note that this version is also stripping `\r` characters from the container's output stream.

---

I was able to make this work on normal Fedora Workstation (silverblue gave me trouble setting up my VM, and I wanted to get to work on the real problem). Please let me know how this goes for you!

I hope it's not out of place for me to say this, but it took me several hours and a lot of effort to understand this problem and work around it. If you find my open source work (like this kind of user support) valuable and are financially able, please consider sponsoring me either on [GitHub](https://github.com/sponsors/whereswaldon/) or [Liberapay](https://github.com/sponsors/whereswaldon/).

**Comment by cnd4** [comment]
Hello,

Thanks for your update, your script works well. I did not see the CRLF problem with this container, I decided to use this one because it seems up to date. 

Thanks for your help, unfortunately this year I'm not able to help any project financially (I lost some contracts because of covid) but I'll considere it when the situation gets better (hopping it won't last ten years).

**Comment by whereswaldon** [comment]
@smumu I'm glad that it works well for you!

No worries about financial stuff! I only mentioned it because this was an unusually large time sink for me. Stay safe and healthy! Feel free to open other feature requests as needed, but I think I prefer to solve this via scripting rather than via making the plugin logic more complex.

Cheers!
